### ISSUE TITLE
Support for Fortify

### ISSUE THREAD

**Issue by pindab0ter** [mpyw/scoped-auth#23]
It seems this extension doesn't support Laravel 9.

When debugging I notice that even though it hits `ScopedAuthServiceProvider::register()`, `ScopedEloquentUserProvider::newModelQuery()` is not called when logging in.

**Comment by mpyw** [comment]
I'll check it out, thanks for reporting

**Comment by mpyw** [comment]
This issue looks to be already closed. Is it working now?

**Comment by pindab0ter** [comment]
Only half. I’m using [Fortify](https://laravel.com/docs/9.x/fortify)’s authentication and I got it working by both adding `Fortify::authenticateUsing` to Fortify's `boot` and using your method. Either didn’t work, both did.

I would much prefer if the first step wasn't required as I want to change as little to the existing authentication flow as possible.

**Comment by mpyw** [comment]
I executed feature/unit tests in my local environment with Laravel 9.x to confirm it works. The issue looks to be Fortify specific.

**Comment by mpyw** [comment]
Sorry to bother you, but would you provide reproducible example repository? I suspect that some part of your `ServiceProvider::register()` has side effects, for instance, resolving Guard instances.

**Comment by mpyw** [comment]
FYI, I think that it would be better:

https://github.com/mpyw/scoped-auth/blob/9d806d0f77dfd23c12bf828bacb55f3af3783201/src/ScopedAuthServiceProvider.php#L17-L23

↓

```php
public function register(): void
{
    if ($this->app->resolved(AuthManager::class)) {
        throw new LogicException('AuthManager must not be resolved at register() cycles. Please confirm your service providers are correct.');
    }
    
    $this->app->afterResolving(AuthManager::class, Closure::fromCallable([$this, 'overrideEloquentUserProvider']));
}

```

**Comment by mpyw** [comment]
Oh... I got it. Fortify's default implementation looks a little terrible...

https://github.com/laravel/fortify/blob/246cf1d01b5481c71c8fe4609396159b7e06393f/src/Actions/RedirectIfTwoFactorAuthenticatable.php#L91-L97

**Comment by mpyw** [comment]
I got it... Fortify's default implementation looks a little terrible.

```php
/**
 * Attempt to validate the incoming credentials.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return mixed
 */
protected function validateCredentials($request)
{
    if (Fortify::$authenticateUsingCallback) {
        return tap(call_user_func(Fortify::$authenticateUsingCallback, $request), function ($user) use ($request) {
            if (! $user) {
                $this->fireFailedEvent($request);

                $this->throwFailedAuthenticationException($request);
            }
        });
    }

    $model = $this->guard->getProvider()->getModel();

    return tap($model::where(Fortify::username(), $request->{Fortify::username()})->first(), function ($user) use ($request) {
        if (! $user || ! $this->guard->getProvider()->validateCredentials($user, ['password' => $request->password])) {
            $this->fireFailedEvent($request, $user);

            $this->throwFailedAuthenticationException($request);
        }
    });
}
```

Actually it should be like this:

```php
/**
 * Attempt to validate the incoming credentials.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return mixed
 */
protected function validateCredentials($request)
{
    if (Fortify::$authenticateUsingCallback) {
        return tap(call_user_func(Fortify::$authenticateUsingCallback, $request), function ($user) use ($request) {
            if (! $user) {
                $this->fireFailedEvent($request);

                $this->throwFailedAuthenticationException($request);
            }
        });
    }

    return tap($this->guard->getProvider()->retrieveByCredentials([
        Fortify::username() => $request->input(Fortify::username()),
    ]), function ($user) use ($request) {
        if (! $user || ! $this->guard->getProvider()->validateCredentials($user, ['password' => $request->password])) {
            $this->fireFailedEvent($request, $user);

            $this->throwFailedAuthenticationException($request);
        }
    });
}
```

**Comment by mpyw** [comment]
WOW, what a nonsense revert!!!!! 😭 

https://github.com/laravel/fortify/pull/318#issuecomment-939763672

**Comment by pindab0ter** [comment]
First off, thanks for taking the time to look into this. Much appreciated!

What's the verdict? Is this a problem on Fortify's end that you can reasonably expect to fix on their end, or is this something you can/have to factor in? Or option C: What could I do with the current setup to get things working using Fortify's `authenticateUsing`?

**Comment by mpyw** [comment]
I think laravel/fortify#195 should be re-reverted, but I'm sure Taylor won't accept it for whatever reason. Therefore, we'll have to deal with `authenticateUsing()`.

If it were me, I would implement it this way:

```php
<?php

namespace App\Auth;

use Illuminate\Http\Request;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Contracts\Auth\StatefulGuard;
use Illuminate\Contracts\Auth\UserProvider;
use Laravel\Fortify\Fortify;

class CustomFortifyAuthenticator
{
    private const PASSWORD_NAME = 'password';
    private readonly UserProvider $provider;

    public function __construct(StatefulGuard $guard)
    {
        $this->provider = $guard->getProvider();
    }

    public function __invoke(Request $request): ?Authenticatable
    {
        $user = $this->provider->retrieveByCredentials([
            Fortify::username() => $request->input(Fortify::username()),
        ]);
        
        return $user && $this->provider->validateCredentials($user, [
            self::PASSWORD_NAME => $request->input(self::PASSWORD_NAME),
        ]) ? $user : null;
    }
}
```

```php
<?php

namespace App\Providers;

use App\Auth\CustomFortifyAuthenticator;
use Illuminate\Support\ServiceProvider;
use Laravel\Fortify\Fortify;

class AuthServiceProvider extends ServiceProvider
{
    public function boot(CustomFortifyAuthenticator $authenticator): void
    {
        Fortify::authenticateUsing($authenticator);
    }
}
```

- I haven't actually tested yet, so maybe I had made a mistake.
- I recommend using `$request->input()` instead of `$request->__get()`. The latter behavior is so confusing. Please refer to the following article through [DeepL](https://www.deepl.com/translator) transaltion.
  - [Laravel の request() や Request::__get() は地雷， Request::input() と Request::route() を使え - Qiita](https://qiita.com/mpyw/items/d26f0ffac1529399a35f)

**Comment by mpyw** [comment]
I'll implement it in this package! thanks

**Comment by pindab0ter** [comment]
Thank you for providing a suggested solution! This will help me in my way.

Have you tried making your case for re-reverting the mentioned change?

**Comment by mpyw** [comment]
@pindab0ter Not yet. It's a long shot, but if you have the perseverance, you can try to send a PR proposing a re-revert with a clear description about this. Thanks!

**Comment by pindab0ter** [comment]
I would, but I don’t have the domain knowledge to support or even come up with any arguments.

**Comment by mpyw** [comment]
I got it, the PR might contain some bugs. Commented here.

https://github.com/laravel/fortify/pull/189#discussion_r906661504

**Comment by pindab0ter** [comment]
Great work! Thanks for doing this!

**Comment by mpyw** [comment]
Unfortunately, Taylor has no plans to make this change at this time.
